version: '3.8'
services:
  redis:
    image: redis:7
    container_name: redis-job-search
    ports:
      - "6379:6379"
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "6000:6000"
    env_file:
      - ./auth-service/.env
      - ./auth-service/.env.dev
    depends_on:
      - redis
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "6001:6001"
    env_file:
      - ./user-service/.env
    depends_on:
      - redis
